import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.calculator': 'Calculator',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'hero.title.line1': 'Expert Mortgage Strategy',
    'hero.title.line2': '& Property Advisory',
    'hero.subtitle': 'Expert Property and mortgage advisory services for you',
    'hero.cta': 'Get Free Report',
    'home.calculator.title': 'Your Mortgage Appraisal',
    'home.calculator.subtitle': 'Get an instant estimate of your borrowing power',
    'home.calculator.annualIncome': 'Annual Income',
    'home.calculator.deposit': 'Deposit Amount',
    'home.calculator.loanTerm': 'Loan Term',
    'home.calculator.interestRate': 'Interest Rate',
    'home.calculator.borrowingCapacity': 'Estimated Total Loan Amount',
    'home.calculator.monthlyRepayment': 'Monthly Repayment',
    'home.calculator.stampDuty': 'Stamp Duty',
    'home.calculator.disclaimer': 'Estimates only. Our experts provide a full professional evaluation.',
    'home.calculator.ctaButton': 'Get Expert Assessment',
    'home.propertyCta.title': 'Ready to find your dream property?',
    'home.propertyCta.description': 'Get expert guidance and personalised property recommendations tailored to your needs',
    'search.location': 'Location',
    'search.propertyType': 'Property Type',
    'search.priceRange': 'Price Range',
    'search.button': 'Search Properties',
    'services.title': 'Our Services',
    'services.property.title': 'Property Buying Advisory',
    'services.property.desc': 'Expert guidance through every step of your property purchase journey',
    'services.mortgage.title': 'Mortgage Advisory',
    'services.mortgage.desc': 'Tailored mortgage solutions to suit your financial needs',
    'services.investment.title': 'Investment Strategy',
    'services.investment.desc': 'Strategic property investment planning for long-term wealth',
    'services.commercial.title': 'Commercial Loans',
    'services.commercial.desc': 'Specialized financing solutions for commercial property investments',
    'services.cta.title': 'Ready to get started?',
    'services.cta.description': 'Discover how our expert advisory services can help you navigate the property market with confidence',
    'calculator.title': 'Property Investment Calculator',
    'calculator.subtitle': 'Calculate your investment returns and understand your financing options',
    'calculator.propertyPrice': 'Property Price',
    'calculator.propertyLocation': 'Property Location',
    'calculator.selectState': 'Select State',
    'calculator.buyingFor': 'Are You Buying For?',
    'calculator.investment': 'Investment',
    'calculator.primaryResidence': 'Primary Residence',
    'calculator.expectedRent': 'Expected Rent Price',
    'calculator.upfrontCost': 'Upfront Cost',
    'calculator.yearlyIncome': 'Yearly Income',
    'calculator.yearlyCost': 'Yearly Cost',
    'calculator.monthlyRepayment': 'Monthly Repayment',
    'calculator.collapse': 'Collapse',
    'calculator.expand': 'Expand',
    'calculator.getReport': 'Get Report',
    'calculator.perWeek': 'Per week',
    'calculator.perMonth': 'Per month',
    'calculator.perYear': 'Per year',
    'calculator.stampDuty': 'Stamp Duty',
    'calculator.fhbExemptionApplied': 'FHB Exemption Applied',
    'calculator.newProperty': 'NEW PROPERTY',
    'calculator.firstHomeBuyer': 'FIRST HOME BUYER',
    'calculator.loanRatio': 'Loan Ratio (LVR)',
    'calculator.loanDetails': 'Loan Details',
    'calculator.loanAmount': 'Loan Amount',
    'calculator.loanInterest': 'Loan Interest',
    'calculator.bestRate': 'Best Ribbon Finance rate',
    'calculator.lockRate': 'Lock in this rate with our experts',
    'calculator.customRate': 'Custom rate',
    'calculator.bestAvailable': 'best available',
    'calculator.interestOnly': 'Interest Only',
    'calculator.principalInterest': 'Principal & Interest',
    'calculator.addLoan': 'Add another loan',
    'calculator.calculatedMonthlyRepayments': 'Calculated Monthly Repayments',
    'calculator.calculatedMonthlyInterest': 'Calculated Monthly Interest',
    'calculator.showAdvanced': 'SHOW ADVANCED MODE',
    'calculator.disclaimer': 'The above references an opinion and is for information purposes only. It is not intended to be investment advice.',
    'about.title': 'About LuxHunter',
    'about.intro': 'Your Trusted Property Advisory Platform',
    'about.desc': 'LuxHunter is a premium property and mortgage advisory platform dedicated to helping clients navigate the Australian property market with confidence. Our expertise spans residential property buying, mortgage advisory, investment strategy, and commercial financing solutions.',
    'about.mission': 'Our Mission',
    'about.missionDesc': 'We believe in providing transparent, professional, and personalized property advisory services. Our platform connects you with expert advice and comprehensive market insights to make informed property decisions.',
    'about.ourValues': 'Our Values',
    'about.values.clientFocused.title': 'Client-Focused',
    'about.values.clientFocused.desc': 'Your goals are our priority. We provide personalized solutions tailored to your unique situation.',
    'about.values.expertGuidance.title': 'Expert Guidance',
    'about.values.expertGuidance.desc': 'Leverage our deep market knowledge and industry expertise for informed decision-making.',
    'about.values.trustedPartnerships.title': 'Trusted Partnerships',
    'about.values.trustedPartnerships.desc': 'Building long-term relationships based on transparency, integrity, and results.',
    'about.values.confidential.title': 'Confidential & Secure',
    'about.values.confidential.desc': 'Your privacy and security are paramount. We handle all information with the utmost care.',
    'about.cta.title': 'Start Your Property Journey Today',
    'about.cta.description': 'Whether you\'re a first-time buyer, seasoned investor, or seeking commercial finance, we\'re here to guide you every step of the way.',
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Get in touch with our team',
    'contact.name': 'Full Name',
    'contact.email': 'Email Address',
    'contact.phone': 'Phone Number',
    'contact.message': 'Your Message',
    'contact.preferred': 'Preferred Contact Method',
    'contact.telegram': 'Telegram',
    'contact.whatsapp': 'WhatsApp',
    'contact.submit': 'Send Message',
    'contact.quickConnect': 'Quick Connect',
    'modal.freeReport.title': 'Get Your Free Property Report',
    'modal.freeReport.subtitle': 'Enter your email to receive a comprehensive property market analysis',
    'modal.freeReport.email': 'Email Address',
    'modal.freeReport.submit': 'Get Free Report',
    'modal.privacy.title': 'Privacy Disclosure',
    'modal.privacy.message': 'We respect your privacy. Your information will be used solely to provide you with the requested property report and relevant market insights. We do not share your data with third parties.',
    'modal.privacy.continue': 'Book a Consultation',
    'modal.privacy.close': 'Close',
    'newsletter.title': 'Stay Updated',
    'newsletter.subtitle': 'Subscribe to receive the latest property insights and market updates',
    'newsletter.name': 'Your Name',
    'newsletter.email': 'Your Email',
    'newsletter.propertyNews': 'Property News & Market Updates',
    'newsletter.personalLoan': 'Personal Loan Updates',
    'newsletter.commercialLoan': 'Commercial Loan Updates',
    'newsletter.subscribe': 'Subscribe',
    'footer.rights': 'All rights reserved',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.disclaimer': 'All financial information on this website is authorised and provided by Ribbon Finance Mortgage Management Pty Ltd (ACL 525880). This website is affiliated with Ribbon Finance. General advice only — not personal financial advice.',
    'success.freeReport': 'Thank you! Your free report request has been received.',
    'success.contact': 'Thank you! We will be in touch soon.',
    'success.newsletter': 'Successfully subscribed to our newsletter!',
    'error.generic': 'Something went wrong. Please try again.',
    'home.featured.title': 'Featured Dream Property',
    'home.featured.subtitle': 'Premium properties across Australia\'s most sought-after locations',
    'home.insights.title': 'Latest Insights',
    'home.insights.subtitle': 'Expert perspectives on the Australian property market',
    'home.testimonials.title': 'What Our Clients Say',
    'home.testimonials.subtitle': 'Trusted by property buyers and investors across Australia',
    'home.enquireNow': 'Enquire Now',
    'home.readMore': 'Read More',
    'home.property.sydney': 'Prestige living in the heart of Sydney',
    'home.property.sydney.location': 'Sydney, NSW',
    'home.property.melbourne': "Discover Melbourne's finest addresses",
    'home.property.melbourne.location': 'Melbourne, VIC',
    'home.property.brisbane': 'Queensland lifestyle at its peak',
    'home.property.brisbane.location': 'Brisbane, QLD',
    'home.news.category.marketUpdate': 'Market Update',
    'home.news.category.financeTips': 'Finance Tips',
    'home.news.category.investment': 'Investment',
    'home.news.article1.date': '9 March 2026',
    'home.news.article1.headline': 'Sydney Property Prices Show Strong Growth in Q1 2026',
    'home.news.article1.excerpt': 'Market analysis reveals continued demand in premium suburbs, with buyers showing renewed confidence in the residential sector.',
    'home.news.article2.date': '7 March 2026',
    'home.news.article2.headline': 'How to Maximize Your Borrowing Capacity in 2026',
    'home.news.article2.excerpt': 'Expert strategies to improve your loan application and secure better rates from Australian lenders in the current market.',
    'home.news.article3.date': '5 March 2026',
    'home.news.article3.headline': 'Top Investment Suburbs to Watch This Year',
    'home.news.article3.excerpt': 'Our research identifies emerging growth areas across Melbourne, Brisbane, and regional markets with strong rental yields.',
    'services.subtitle': 'Comprehensive property and financial solutions designed to help you achieve your real estate goals with confidence and clarity.',
    'services.property.feature1': 'Market analysis and property evaluation',
    'services.property.feature2': 'Negotiation support and bidding strategy',
    'services.property.feature3': 'Due diligence and property inspection coordination',
    'services.property.feature4': 'Settlement assistance and handover support',
    'services.mortgage.feature1': 'Competitive rate comparison across lenders',
    'services.mortgage.feature2': 'Pre-approval assistance and documentation',
    'services.mortgage.feature3': 'Loan structure optimization for your situation',
    'services.mortgage.feature4': 'Ongoing support throughout the process',
    'services.investment.feature1': 'Portfolio diversification strategies',
    'services.investment.feature2': 'Growth area identification and analysis',
    'services.investment.feature3': 'Rental yield and capital growth forecasting',
    'services.investment.feature4': 'Tax optimization and depreciation advice',
    'services.commercial.feature1': 'Commercial property financing solutions',
    'services.commercial.feature2': 'Business loan and equipment finance',
    'services.commercial.feature3': 'Development and construction lending',
    'services.commercial.feature4': 'Refinancing and debt consolidation',
    'chat.button': 'Chat with expert',
    'home.testimonials.sarah.quote': 'LuxHunter helped us navigate the complex mortgage process with ease. Their expert guidance saved us thousands and got us into our dream home in Mosman.',
    'home.testimonials.sarah.name': 'Sarah M.',
    'home.testimonials.sarah.location': 'Mosman, NSW',
    'home.testimonials.james.quote': 'Outstanding service from start to finish. The team found us the perfect investment property and secured incredibly competitive loan rates.',
    'home.testimonials.james.name': 'James L.',
    'home.testimonials.james.location': 'Toorak, VIC',
    'home.testimonials.michelle.quote': "Professional, responsive, and genuinely cared about our financial goals. We couldn't have asked for better property advisors.",
    'home.testimonials.michelle.name': 'Michelle T.',
    'home.testimonials.michelle.location': 'Ascot, QLD',
  },
  zh: {
    'nav.home': '首页',
    'nav.services': '服务',
    'nav.calculator': '计算器',
    'nav.about': '关于',
    'nav.contact': '联系',
    'hero.title.line1': '专业房产策略',
    'hero.title.line2': '与贷款顾问',
    'hero.subtitle': '为您提供专业的房产顾问与贷款咨询服务',
    'hero.cta': '获取免费报告',
    'home.calculator.title': '您的按揭估计表',
    'home.calculator.subtitle': '对您的借贷能力 一目了然',
    'home.calculator.annualIncome': '年收入',
    'home.calculator.deposit': '银行存款',
    'home.calculator.loanTerm': '按揭年份',
    'home.calculator.interestRate': '按揭利息',
    'home.calculator.borrowingCapacity': '估计借贷总金额',
    'home.calculator.monthlyRepayment': '每月还贷额',
    'home.calculator.stampDuty': '印花税',
    'home.calculator.disclaimer': '估计您的借贷：我们的持牌专家会给你一个专业的评估报告',
    'home.calculator.ctaButton': '获得专业评估',
    'home.propertyCta.title': '让我们帮您获得心仪的房产？',
    'home.propertyCta.description': '我们会安排专家根据您的要求，为您提供专业的咨询建议',
    'search.location': '地点',
    'search.propertyType': '房产类型',
    'search.priceRange': '价格范围',
    'search.button': '搜索房产',
    'services.title': '我们的服务',
    'services.property.title': '购房咨询',
    'services.property.desc': '在您购房旅程的每一步提供专业指导',
    'services.mortgage.title': '贷款咨询',
    'services.mortgage.desc': '量身定制的贷款解决方案以满足您的财务需求',
    'services.investment.title': '投资策略',
    'services.investment.desc': '长期财富的战略性房产投资规划',
    'services.commercial.title': '商业贷款',
    'services.commercial.desc': '商业房产投资的专业融资解决方案',
    'services.cta.title': '让我们帮您获得心仪的房产？',
    'services.cta.description': '让我们的持牌专家帮您更有信心地获得心仪的房产',
    'calculator.title': '房产投资计算器',
    'calculator.subtitle': '一目了然您的投资贷款比',
    'calculator.propertyPrice': '房产价格',
    'calculator.propertyLocation': '房产所在地',
    'calculator.selectState': '选择州',
    'calculator.buyingFor': '购买目的？',
    'calculator.investment': '投资',
    'calculator.primaryResidence': '自住',
    'calculator.expectedRent': '预期租金',
    'calculator.upfrontCost': '首附费用',
    'calculator.yearlyIncome': '年收入',
    'calculator.yearlyCost': '年支出',
    'calculator.monthlyRepayment': '月还款额',
    'calculator.collapse': '收起',
    'calculator.expand': '展开',
    'calculator.getReport': '获取报告',
    'calculator.perWeek': '每周',
    'calculator.perMonth': '每月',
    'calculator.perYear': '每年',
    'calculator.stampDuty': '印花税',
    'calculator.fhbExemptionApplied': '首次购房者豁免已应用',
    'calculator.newProperty': '新房产',
    'calculator.firstHomeBuyer': '首次购房者',
    'calculator.loanRatio': '贷款比率 (LVR)',
    'calculator.loanDetails': '贷款详情',
    'calculator.loanAmount': '贷款金额',
    'calculator.loanInterest': '贷款利率',
    'calculator.bestRate': '最佳 Ribbon Finance 利率',
    'calculator.lockRate': '与我们的专家锁定此利率',
    'calculator.customRate': '自定义利率',
    'calculator.bestAvailable': '最佳可用',
    'calculator.interestOnly': '只付利息',
    'calculator.principalInterest': '本息同还',
    'calculator.addLoan': '添加另一笔贷款',
    'calculator.calculatedMonthlyRepayments': '计算月还款额',
    'calculator.calculatedMonthlyInterest': '计算月利息',
    'calculator.showAdvanced': '显示高级模式',
    'calculator.disclaimer': '以上内容仅供参考，不构成投资建议。',
    'about.title': '关于LuxHunter',
    'about.intro': '您值得信赖的房产咨询平台',
    'about.desc': 'LuxHunter 是一个高端房产和贷款咨询平台，致力于帮助客户自信地驾驭澳大利亚房地产市场。我们的专业知识涵盖住宅购买、贷款咨询、投资策略和商业融资解决方案。',
    'about.mission': '我们的使命',
    'about.missionDesc': '我们相信提供透明、专业和个性化的房产咨询服务。我们的平台为您提供专业建议和全面的市场洞察，帮助您做出明智的房产决策。',
    'about.ourValues': '我们的价值观',
    'about.values.clientFocused.title': '以客户为中心',
    'about.values.clientFocused.desc': '您的目标是我们的首要任务。我们提供针对您独特情况量身定制的个性化解决方案。',
    'about.values.expertGuidance.title': '专业指导',
    'about.values.expertGuidance.desc': '利用我们深厚的市场知识和行业专业知识，做出明智的决策。',
    'about.values.trustedPartnerships.title': '值得信赖的合作伙伴',
    'about.values.trustedPartnerships.desc': '基于透明度、诚信和成果建立长期关系。',
    'about.values.confidential.title': '保密与安全',
    'about.values.confidential.desc': '您的隐私和安全至关重要。我们以最谨慎的态度处理所有信息。',
    'about.cta.title': '立即开始您的房产之旅',
    'about.cta.description': '无论您是首次购房者、经验丰富的投资者还是寻求商业融资，我们都会在每一步为您提供指导。',
    'contact.title': '联系我们',
    'contact.subtitle': '与我们的团队取得联系',
    'contact.name': '全名',
    'contact.email': '电子邮件地址',
    'contact.phone': '电话号码',
    'contact.message': '您的留言',
    'contact.preferred': '首选联系方式',
    'contact.telegram': 'Telegram',
    'contact.whatsapp': 'WhatsApp',
    'contact.submit': '发送消息',
    'contact.quickConnect': '快速联系',
    'modal.freeReport.title': '获取免费房产报告',
    'modal.freeReport.subtitle': '输入您的电子邮件以接收全面的房产市场分析',
    'modal.freeReport.email': '电子邮件地址',
    'modal.freeReport.submit': '获取免费报告',
    'modal.privacy.title': '隐私声明',
    'modal.privacy.message': '我们尊重您的隐私。您的信息将仅用于为您提供所需的房产报告和相关市场见解。我们不会与第三方分享您的数据。',
    'modal.privacy.continue': '预约咨询',
    'modal.privacy.close': '关闭',
    'newsletter.title': '保持更新',
    'newsletter.subtitle': '订阅以接收最新的房产见解和市场更新',
    'newsletter.name': '您的姓名',
    'newsletter.email': '您的电子邮件',
    'newsletter.propertyNews': '房产新闻和市场更新',
    'newsletter.personalLoan': '个人贷款更新',
    'newsletter.commercialLoan': '商业贷款更新',
    'newsletter.subscribe': '订阅',
    'footer.rights': '版权所有',
    'footer.privacy': '隐私政策',
    'footer.terms': '服务条款',
    'footer.disclaimer': '本网站所有财务信息均由 Ribbon Finance Mortgage Management Pty Ltd（ACL 525880）授权提供。本网站隶属于 Ribbon Finance。仅供一般建议之用，非个人财务建议。',
    'success.freeReport': '谢谢！我们已收到您的免费报告请求。',
    'success.contact': '谢谢！我们会尽快与您联系。',
    'success.newsletter': '成功订阅我们的新闻通讯！',
    'error.generic': '出了点问题。请重试。',
    'home.featured.title': '精选梦想房产',
    'home.featured.subtitle': '澳大利亚最受欢迎地区的优质房产',
    'home.insights.title': '最新资讯',
    'home.insights.subtitle': '关于澳大利亚房地产市场的专家观点',
    'home.testimonials.title': '客户评价',
    'home.testimonials.subtitle': '深受澳大利亚房产买家和投资者信赖',
    'home.enquireNow': '立即咨询',
    'home.readMore': '阅读更多',
    'home.property.sydney': '悉尼市中心的尊贵生活',
    'home.property.sydney.location': '悉尼, 新南威尔士州',
    'home.property.melbourne': '探索墨尔本的顶级地段',
    'home.property.melbourne.location': '墨尔本, 维多利亚州',
    'home.property.brisbane': '昆士兰州的巅峰生活方式',
    'home.property.brisbane.location': '布里斯班, 昆士兰州',
    'home.news.category.marketUpdate': '市场更新',
    'home.news.category.financeTips': '理财技巧',
    'home.news.category.investment': '投资',
    'home.news.article1.date': '2026年3月9日',
    'home.news.article1.headline': '悉尼房价在2026年第一季度显示强劲增长',
    'home.news.article1.excerpt': '市场分析显示，高端郊区持续需求旺盛，买家对住宅市场信心增强。',
    'home.news.article2.date': '2026年3月7日',
    'home.news.article2.headline': '如何在2026年最大化您的借款能力',
    'home.news.article2.excerpt': '专家策略帮助改善贷款申请，在当前市场中从澳大利亚贷款机构获得更优惠的利率。',
    'home.news.article3.date': '2026年3月5日',
    'home.news.article3.headline': '今年值得关注的顶级投资郊区',
    'home.news.article3.excerpt': '我们的研究识别墨尔本、布里斯班和区域市场中的新兴增长区域，具有强劲的租金收益。',
    'services.subtitle': '全面的房产和金融解决方案，帮助您自信、清晰地实现房地产目标。',
    'services.property.feature1': '市场分析和房产评估',
    'services.property.feature2': '谈判支持和竞标策略',
    'services.property.feature3': '尽职调查和房产检查协调',
    'services.property.feature4': '交割协助和交接支持',
    'services.mortgage.feature1': '贷款机构之间的竞争性利率比较',
    'services.mortgage.feature2': '预批准协助和文件准备',
    'services.mortgage.feature3': '根据您的情况优化贷款结构',
    'services.mortgage.feature4': '整个过程中的持续支持',
    'services.investment.feature1': '投资组合多元化策略',
    'services.investment.feature2': '增长区域识别和分析',
    'services.investment.feature3': '租金收益和资本增长预测',
    'services.investment.feature4': '税务优化和折旧建议',
    'services.commercial.feature1': '商业房产融资解决方案',
    'services.commercial.feature2': '商业贷款和设备融资',
    'services.commercial.feature3': '开发和建设贷款',
    'services.commercial.feature4': '再融资和债务整合',
    'chat.button': '与专家聊天',
    'home.testimonials.sarah.quote': 'LuxHunter帮助我们轻松完成了复杂的按揭流程。他们的专业指导为我们节省了数千澳元，让我们在莫斯曼拥有了梦想中的家。',
    'home.testimonials.sarah.name': 'Sarah M.',
    'home.testimonials.sarah.location': '莫斯曼, 新南威尔士州',
    'home.testimonials.james.quote': '从头到尾的卓越服务。团队为我们找到了完美的投资房产，并获得了极具竞争力的贷款利率。',
    'home.testimonials.james.name': 'James L.',
    'home.testimonials.james.location': '图拉克, 维多利亚州',
    'home.testimonials.michelle.quote': '专业、响应迅速，真正关心我们的财务目标。我们找不到更好的房产顾问了。',
    'home.testimonials.michelle.name': 'Michelle T.',
    'home.testimonials.michelle.location': '阿斯科特, 昆士兰州',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
